name: Forced Release Workflow

on:
  workflow_dispatch:

jobs:
  release:
    name: Forced Release
    runs-on: ubuntu-latest

    env:
      CI: true
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - uses: actions/checkout@main
      with:
       fetch-depth: 0

    - uses: fregante/setup-git-user@v1

    - name: Load dependencies versions
      id: versions
      run: |
        echo "node=$(sed -ne '/\"engines\":/,/},/p' ./package.json | sed -ne 's/^\s*\"node\": \"\\|\",$//gp')" >> $GITHUB_OUTPUT

    - uses: actions/setup-node@master
      with:
        node-version: ${{ steps.versions.outputs.node }}
        cache: 'npm' # save global npm install cache

    - name: Add node_modules to PATH env
      run: npm bin >> $GITHUB_PATH

    - name: Generate Dependencies Cache
      id: dependencies
      uses: actions/cache@main
      with:
        path: node_modules
        key: ${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.dependencies.outputs.cache-hit != 'true'
      run: npm clean-install

    - name: Run release latest
      if: github.ref == 'refs/heads/main'
      run: lerna publish from-package --yes

    - name: Run release old majors
      if: (startsWith(github.ref, 'refs/heads/v') && endsWith(github.ref, '.x'))
      run: lerna publish from-package --yes
